name = "lustre_ssg"
version = "0.2.0"
description = "A simple static site generator for Lustre projects."

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre_ssg" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.32"
lustre = "~> 3.0"
simplifile = "~> 0.3.0"

[dev-dependencies]
gleeunit = "~> 0.10"
