name = "lustre_ssg"
version = "0.12.0"
description = "A simple static site generator for Lustre projects."
gleam = ">= 1.6.0"

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "ssg" }
links = [
    { title = "Website", href = "https://lustre.build" },
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

[dependencies]
filepath = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.34.0"
jot = ">= 5.0.0 and < 6.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
tom = ">= 1.0.0 and < 3.0.0"
