name = "lustre_ssg"
version = "0.5.0"
description = "A simple static site generator for Lustre projects."

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "ssg" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.34"
lustre = "~> 3.0 or ~> 4.0 or 4.0.0-rc.2"
simplifile = "~> 1.0"
jot = "~> 0.2"
tom = "~> 0.3"

[dev-dependencies]
gleeunit = "~> 1.0"
